sudo: requried
language: generic 
services:
  - docker
  
before_install: 
  - docker build -t yashassamaga/react-test -f ./client/Dockerfile.dev ./client
  

script:
  - docker run yashassamaga/react-test npm run test -- --coverage
  
after_success:
  - docker build -t yashassamaga/multi-client ./client
  - docker build -t yashassamaga/multi-nginx ./nginx
  - docker build -t yashassamaga/multi-server ./server
  - docker build -t yashassamaga/multi-worker ./worker
#login to docker hub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  
#take those images and push it to docker hub
  - docker push  yashassamaga/multi-client
  - docker push  yashassamaga/multi-nginx
  - docker push  yashassamaga/multi-server
  - docker push  yashassamaga/multi-worker
  
deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "multi-docker"
  env: "Multidocker-env"
  bucket_name: "elasticbeanstalk-us-east-2-306506089118"
  bucket_path: "docker-multi"
  on:
    branch: main
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"
  
  
